require('dotenv').config();

const express = require('express');
const cors = require('cors');
const { Readable } = require('node:stream');

const {
  DCTM_REST_BASE = '',
  DCTM_USER = '',
  DCTM_PASS = '',
  PORT = 4000,
  FRONTEND_ORIGIN = 'http://localhost:5173',
} = process.env;

// Base URL of the ECM Chat-with-Document service (a separate FastAPI backend
// that indexes Documentum content and answers questions about one object).
const CHAT_API_BASE = process.env.CHAT_API_BASE || 'http://localhost:8001';

// Chat answers are generated by an LLM and can take much longer than the
// regular Documentum proxy requests, so give them a longer timeout.
const CHAT_TIMEOUT_MS = Number(process.env.CHAT_TIMEOUT_MS || 180000);

// Documentum REST Services uses a vendor-specific JSON media type. Plain
// "application/json" is rejected (HTTP 500), so we must use this everywhere.
const JSON_MEDIA_TYPE = 'application/vnd.emc.documentum+json';

// Node's fetch sends "Accept-Language: *" by default, which Documentum rejects
// with "Invalid or unsupported locale string" (HTTP 500). Pin a real locale.
const ACCEPT_LANGUAGE = 'en-US';

const app = express();

// Dev-only: allow any origin. This is safe while the proxy is only listening
// on localhost and used for local development. If this ever faces the public
// internet, switch back to a whitelist:
//   app.use(cors({ origin: FRONTEND_ORIGIN.split(',').map((s) => s.trim()) }));
app.use(cors({ origin: true, credentials: true }));
app.use(express.json());

// Credentials entered on the login page live here (in memory only).
let sessionCredentials = null;

// Use the logged-in session credentials if present, otherwise fall back to
// whatever is configured in backend/.env.
function currentCredentials() {
  if (sessionCredentials) return sessionCredentials;
  if (DCTM_USER && DCTM_PASS) return { username: DCTM_USER, password: DCTM_PASS };
  return null;
}

// Basic auth is applied server-side so credentials never leave the proxy.
function authHeader() {
  const c = currentCredentials();
  return 'Basic ' + Buffer.from(`${c.username}:${c.password}`).toString('base64');
}

// Reject early (with a clear message) if the proxy isn't configured / signed in.
function configError() {
  if (!DCTM_REST_BASE) {
    return 'DCTM_REST_BASE is not set. Add it to backend/.env and restart the proxy.';
  }
  if (!currentCredentials()) {
    return 'Not signed in. Provide credentials on the login page (or set DCTM_USER/DCTM_PASS in backend/.env).';
  }
  return null;
}

// Abort upstream requests that hang, so a dead Documentum host fails fast
// instead of leaving the browser (and the login) stuck waiting.
const REQUEST_TIMEOUT_MS = 30000;

function fetchWithTimeout(url, options, timeoutMs = REQUEST_TIMEOUT_MS) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(url, { ...options, signal: controller.signal }).finally(() =>
    clearTimeout(timer)
  );
}

function upstreamError(err) {
  if (err && err.name === 'AbortError') {
    return { status: 504, error: 'Timed out waiting for the Documentum server.' };
  }
  return { status: 502, error: 'Could not reach the Documentum server', message: err.message };
}

// --- Logging ---
// LOG_LEVEL controls verbosity: silent | info | debug.
//   info  -> logs every upstream request/response (method, URL, status, size)
//   debug -> also logs request/response bodies (truncated)
const LOG_LEVEL = (process.env.LOG_LEVEL || 'info').toLowerCase();

function ts() {
  return new Date().toISOString();
}

function maskAuth(value) {
  if (!value) return 'none';
  if (value.startsWith('Basic ')) return 'Basic ****';
  return '****';
}

function logUpstreamRequest(method, url, authValue, body) {
  if (LOG_LEVEL === 'silent') return;
  console.log(`[${ts()}] → ${method} ${url}  auth=${maskAuth(authValue)}`);
  if (LOG_LEVEL === 'debug' && body) {
    console.log(`[${ts()}]   request body: ${truncate(body)}`);
  }
}

function logUpstreamResponse(status, contentType, size, durationMs) {
  if (LOG_LEVEL === 'silent') return;
  const sizeLabel = size == null ? '-' : `${size} bytes`;
  console.log(
    `[${ts()}] ← ${status}  ${contentType || '-'}  ${sizeLabel}  ${durationMs}ms`
  );
}

function debugBody(label, text) {
  if (LOG_LEVEL !== 'debug' || !text) return;
  console.log(`[${ts()}]   ${label}: ${truncate(text)}`);
}

function truncate(text, max = 2000) {
  const s = String(text);
  return s.length > max ? `${s.slice(0, max)}… (${s.length} chars total)` : s;
}

// Serialize an Express query object back into a query string. Used to forward
// arbitrary query params (inline, paging, include-total, …) to Documentum 1:1.
function buildQuery(params) {
  if (!params) return '';
  const qs = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null || value === '') continue;
    if (Array.isArray(value)) value.forEach((v) => qs.append(key, v));
    else qs.append(key, value);
  }
  const s = qs.toString();
  return s ? `?${s}` : '';
}

// Forward a JSON request/response to the Documentum REST endpoint.
async function forwardJson(req, res, upstreamPath) {
  const cfgErr = configError();
  if (cfgErr) {
    return res.status(500).json({ error: cfgErr });
  }

  const url = `${DCTM_REST_BASE}${upstreamPath}`;
  const auth = authHeader();
  const headers = {
    Authorization: auth,
    Accept: JSON_MEDIA_TYPE,
    'Accept-Language': ACCEPT_LANGUAGE,
  };

  const options = { method: req.method, headers };
  if (req.method === 'POST' && req.body) {
    headers['Content-Type'] = JSON_MEDIA_TYPE;
    options.body = JSON.stringify(req.body);
  }

  logUpstreamRequest(req.method, url, auth, options.body);

  try {
    const start = Date.now();
    const upstream = await fetchWithTimeout(url, options);
    const raw = await upstream.text();

    logUpstreamResponse(
      upstream.status,
      upstream.headers.get('content-type'),
      raw.length,
      Date.now() - start
    );
    debugBody('response body', raw);

    let payload;
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }

    if (!upstream.ok) {
      // Documentum error bodies look like { status, code, message, details, id }.
      // Preserve code/details so the UI can show a readable, actionable error.
      const body = payload && typeof payload === 'object' ? payload : null;
      const message =
        (body && (body.message || body.error)) ||
        (typeof payload === 'string' ? payload : `Upstream responded with ${upstream.status}`);
      return res.status(upstream.status).json({
        error: `Documentum responded with ${upstream.status}`,
        code: body && body.code ? body.code : undefined,
        message,
        details: body && body.details ? body.details : undefined,
      });
    }

    // Normalize to plain JSON for the frontend (Documentum returns the vendor
    // media type, which the browser would otherwise treat as opaque text).
    res.status(upstream.status).type('application/json').send(payload);
  } catch (err) {
    const e = upstreamError(err);
    res.status(e.status).json(e);
  }
}

// Stream a binary response (document content) without buffering it in memory.
async function forwardContent(req, res, upstreamPath) {
  const cfgErr = configError();
  if (cfgErr) {
    return res.status(500).json({ error: cfgErr });
  }

  const url = `${DCTM_REST_BASE}${upstreamPath}`;
  const auth = authHeader();
  logUpstreamRequest('GET', url, auth);

  try {
    const start = Date.now();
    const upstream = await fetchWithTimeout(url, {
      method: 'GET',
      headers: { Authorization: auth, 'Accept-Language': ACCEPT_LANGUAGE },
    });

    const contentType = upstream.headers.get('content-type');
    const contentLength = upstream.headers.get('content-length');
    logUpstreamResponse(
      upstream.status,
      contentType,
      contentLength != null ? Number(contentLength) : null,
      Date.now() - start
    );

    if (!upstream.ok) {
      const raw = await upstream.text();
      let message = raw;
      try {
        message = JSON.parse(raw).message || raw;
      } catch {
        /* not JSON */
      }
      return res.status(upstream.status).json({
        error: `Documentum responded with ${upstream.status}`,
        message,
      });
    }

    const contentDisposition = upstream.headers.get('content-disposition');

    if (contentType) res.set('Content-Type', contentType);
    if (contentDisposition) res.set('Content-Disposition', contentDisposition);
    if (contentLength) res.set('Content-Length', contentLength);

    if (upstream.body) {
      Readable.fromWeb(upstream.body).pipe(res);
    } else {
      res.end();
    }
  } catch (err) {
    const e = upstreamError(err);
    res.status(e.status).json(e);
  }
}

// Forward a request to the ECM Chat-with-Document service. Unlike Documentum,
// this service speaks plain application/json and needs no Basic auth — it is an
// independent FastAPI backend that fetches/indexes the document itself.
async function forwardChat(req, res, method, path) {
  if (!CHAT_API_BASE) {
    return res
      .status(500)
      .json({ error: 'CHAT_API_BASE is not set. Add it to backend/.env and restart the proxy.' });
  }

  const url = `${CHAT_API_BASE}${path}${buildQuery(req.query)}`;
  const headers = { Accept: 'application/json' };
  const options = { method, headers };

  if (req.body && (method === 'POST' || method === 'PUT' || method === 'PATCH')) {
    headers['Content-Type'] = 'application/json';
    options.body = JSON.stringify(req.body);
  }

  logUpstreamRequest(method, url, null, options.body);

  try {
    const start = Date.now();
    const upstream = await fetchWithTimeout(url, options, CHAT_TIMEOUT_MS);
    const raw = await upstream.text();

    logUpstreamResponse(
      upstream.status,
      upstream.headers.get('content-type'),
      raw.length,
      Date.now() - start
    );
    debugBody('response body', raw);

    let payload;
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }

    if (!upstream.ok) {
      // FastAPI error bodies are { detail: "..." } (HTTPException) or
      // { detail: [ { msg, loc, ... } ] } (validation errors).
      const body = payload && typeof payload === 'object' ? payload : null;
      let message = typeof payload === 'string' ? payload : `Upstream responded with ${upstream.status}`;
      if (body && typeof body.detail === 'string') {
        message = body.detail;
      } else if (body && Array.isArray(body.detail) && body.detail.length) {
        message = body.detail.map((d) => d.msg || JSON.stringify(d)).join('; ');
      }
      return res.status(upstream.status).json({
        error: `Chat service responded with ${upstream.status}`,
        message,
      });
    }

    res.status(upstream.status).type('application/json').send(payload);
  } catch (err) {
    const e = upstreamError(err);
    res.status(e.status).json(e);
  }
}

// --- Authentication (login page) ---

app.get('/api/auth/status', (req, res) => {
  res.json({ loggedIn: !!currentCredentials() });
});

app.post('/api/auth/login', async (req, res) => {
  const { username, password } = req.body || {};
  if (!username || !password) {
    return res.status(400).json({ error: 'Username and password are required.' });
  }
  if (!DCTM_REST_BASE) {
    return res.status(500).json({
      error: 'DCTM_REST_BASE is not set. Add it to backend/.env and restart the proxy.',
    });
  }

  const token = Buffer.from(`${username}:${password}`).toString('base64');
  const auth = `Basic ${token}`;
  logUpstreamRequest('GET', DCTM_REST_BASE, auth);

  try {
    const start = Date.now();
    const upstream = await fetchWithTimeout(DCTM_REST_BASE, {
      headers: { Authorization: auth, Accept: JSON_MEDIA_TYPE, 'Accept-Language': ACCEPT_LANGUAGE },
    });

    logUpstreamResponse(upstream.status, upstream.headers.get('content-type'), null, Date.now() - start);

    if (upstream.status === 401 || upstream.status === 403) {
      return res.status(401).json({ error: 'Invalid username or password.' });
    }
    if (!upstream.ok) {
      const raw = await upstream.text();
      let message = raw;
      try {
        const data = JSON.parse(raw);
        message = data.message || data.details || raw;
      } catch {
        /* not JSON */
      }
      return res.status(upstream.status).json({
        error: `Documentum responded with ${upstream.status}`,
        message,
      });
    }

    sessionCredentials = { username, password };

    let name = '';
    try {
      const data = await upstream.json();
      name = data.name || data.title || '';
    } catch {
      /* non-JSON body; name stays empty */
    }

    res.json({ ok: true, username, name });
  } catch (err) {
    const e = upstreamError(err);
    res.status(e.status).json(e);
  }
});

app.post('/api/auth/logout', (req, res) => {
  sessionCredentials = null;
  res.json({ ok: true });
});

// --- Routes (mirror Documentum REST 1:1) ---

// Repository metadata
app.get('/api/repository', (req, res) => forwardJson(req, res, ''));

// Cabinets (top level of the tree) — fetched via DQL so we can filter on
// is_private = false. Cabinets are folder subtypes, so their children and
// documents are reached through the /folders/:id endpoints below.
app.get('/api/dql', (req, res) => {
  const dql = req.query.dql;
  if (!dql) {
    return res.status(400).json({ error: 'Missing "dql" query parameter.' });
  }
  // Documentum exposes DQL as a query parameter on the repository root
  // (linkrel "dql" → {BASE}{?dql}), not as a /dql path segment.
  return forwardJson(req, res, `?dql=${encodeURIComponent(dql)}`);
});

// Folders (cabinets are subtypes of folders, so the tree and contents tables
// both use these endpoints regardless of whether the node is a cabinet).
app.get('/api/folders/:id', (req, res) => forwardJson(req, res, `/folders/${req.params.id}`));

// Without inline=true these collection feeds only return link "summary" entries
// (no content.properties), which would leave names/ids blank in the UI.
app.get('/api/folders/:id/folders', (req, res) =>
  forwardJson(req, res, `/folders/${req.params.id}/folders?inline=true`)
);

// Documents also need an explicit view: the default inline view omits
// object_name and r_content_size for documents.
const DOC_VIEW =
  'r_object_id,object_name,r_object_type,a_content_type,r_modify_date,r_content_size,r_full_content_size';
app.get('/api/folders/:id/documents', (req, res) =>
  forwardJson(req, res, `/folders/${req.params.id}/documents?inline=true&view=${encodeURIComponent(DOC_VIEW)}`)
);

// DQL queries (POST form)
app.post('/api/queries', (req, res) => forwardJson(req, res, '/queries'));

// Objects (properties + content stream)
app.get('/api/objects/:id', (req, res) => forwardJson(req, res, `/objects/${req.params.id}`));
app.get('/api/objects/:id/content-media', (req, res) => forwardContent(req, res, `/objects/${req.params.id}/content-media`));

// --- Chat with Document (ECM Chat-with-Document service) ---

// Warm up the in-memory/persistent index for a single document.
app.post('/api/index/:id', (req, res) =>
  forwardChat(req, res, 'POST', `/api/index/${req.params.id}`)
);

// Whether the document is indexed in the requested mode (?mode=memory).
app.get('/api/index/:id/status', (req, res) =>
  forwardChat(req, res, 'GET', `/api/index/${req.params.id}/status`)
);

// Ask a question about a document (optionally with conversation history).
app.post('/api/chat/:id', (req, res) =>
  forwardChat(req, res, 'POST', `/api/chat/${req.params.id}`)
);

// --- Advanced Search ---

// Object types (searchable dropdown). The plain /types feed only carries the
// system type name, so instead run one DQL query against the data dictionary
// (dmi_dd_type_info) to fetch each type's human-readable label_text alongside
// its type_name, and normalize the result into a flat [{ name, label }] list.
app.get('/api/types', async (req, res) => {
  const cfgErr = configError();
  if (cfgErr) return res.status(500).json({ error: cfgErr });

  const dql = 'select label_text, type_name from dmi_dd_type_info order by type_name';
  const url = `${DCTM_REST_BASE}?dql=${encodeURIComponent(dql)}`;
  const auth = authHeader();
  logUpstreamRequest('GET', url, auth);

  try {
    const start = Date.now();
    const upstream = await fetchWithTimeout(url, {
      headers: { Authorization: auth, Accept: JSON_MEDIA_TYPE, 'Accept-Language': ACCEPT_LANGUAGE },
    });
    const raw = await upstream.text();
    logUpstreamResponse(upstream.status, upstream.headers.get('content-type'), raw.length, Date.now() - start);
    debugBody('response body', raw);

    let payload;
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }

    if (!upstream.ok) {
      const body = payload && typeof payload === 'object' ? payload : null;
      const message =
        (body && (body.message || body.error)) ||
        (typeof payload === 'string' ? payload : `Upstream responded with ${upstream.status}`);
      return res.status(upstream.status).json({
        error: `Documentum responded with ${upstream.status}`,
        code: body && body.code ? body.code : undefined,
        message,
        details: body && body.details ? body.details : undefined,
      });
    }

    const entries = (payload && payload.entries) || [];
    const types = entries
      .map((entry) => {
        const props = (entry && entry.content && entry.content.properties) || (entry && entry.properties) || {};
        const name = props.type_name || (entry && entry.title) || '';
        const label = props.label_text || name;
        return { name, label };
      })
      .filter((t) => t.name)
      .sort((a, b) => String(a.name).localeCompare(String(b.name)));

    res.type('application/json').json(types);
  } catch (err) {
    const e = upstreamError(err);
    res.status(e.status).json(e);
  }
});

// A single type's attribute metadata (name, data type, repeating flag) — used
// to populate the attribute dropdown and filter operators by data type.
app.get('/api/types/:type', (req, res) => forwardJson(req, res, `/types/${req.params.type}`));

// Search. The body is built by the frontend query builder; query params
// (items-per-page, page, inline, include-total) are forwarded untouched.
app.post('/api/search', (req, res) => forwardJson(req, res, `/search${buildQuery(req.query)}`));

// Serve the standalone Ext JS Advanced Search frontend (sibling project) so it
// shares this proxy's origin and can call /api/* directly without CORS.
app.use(express.static(require('path').resolve(__dirname, '..', '..', 'DocumentumSearchExt')));

app.listen(PORT, () => {
  console.log(`Documentum proxy listening on http://localhost:${PORT}`);
  console.log(`Upstream base: ${DCTM_REST_BASE || '(not set — edit backend/.env)'}`);
  if (!DCTM_USER || !DCTM_PASS) {
    console.warn('Note: DCTM_USER / DCTM_PASS are empty. Sign in via the login page to browse.');
  }
});
