#------------------- Log4j2 internals  --------------------------
#The level of internal Log4j events that should be logged to the console.
# Valid values for this attribute are "trace", "debug", "info", "warn",
# "error" and "fatal"
status=error
#Either "err" for stderr, "out" for stdout, a file path, or a URL.
dest=err
#The name of the configuration.
name=PropertiesConfig
monitorInterval=5

rootLogger.level=WARN
rootLogger.appenderRefs=A1,F1
rootLogger.appenderRef.A1.ref=STDOUT
rootLogger.appenderRef.F1.ref=RollingFile

# Enable logging inside your application classes.
# XCP classes
logger.xcp.name=com.emc.xcp
logger.xcp.level=WARN

# ------- WARNING ------------------------------------
# For security purposes, do not allow any messages in the log file from the security package.
# Some logged messages from this package may contain valid user names.
# Logging in this package should be enabled for development environments only.
logger.xcprestcore.name=com.emc.xcp.rest.core
logger.xcprestcore.level=WARN

logger.xcprestsecurity.name=com.emc.xcp.rest.security
logger.xcprestsecurity.level=WARN

# JPA
logger.persistencedocumentum.name=com.emc.xcp.persistence.documentum
logger.persistencedocumentum.level=WARN

# Spring
logger.spring.name=org.springframework
logger.spring.level=WARN

# DFC
logger.dfc.name=com.documentum
logger.dfc.level=WARN

# Production Debugger
logger.pd.name=com.emc.xcp.services.pd
logger.pd.level=WARN

# default is set to be a ConsoleAppender.
# default uses PatternLayout.
appender.A1.type=Console
appender.A1.name=STDOUT
appender.A1.layout.type=PatternLayout
# [Timestamp] [Trace Level] [P<ID>][T<ID>] [Context ID] [Context name] Message
# [      %d ] [        %p ] [  ?? ][  %t ] [ %X       ] [ %c         ] %m%n
appender.A1.layout.pattern=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %5p [T%t] [%x] [%C:%L] %m%n


#------------------- Application services log --------------------------
appender.F1.type=RollingFile
appender.F1.name=RollingFile
appender.F1.fileName=C:/temp/documentum/xCPApplication.log
appender.F1.filePattern=C:/temp/documentum/xCPApplication-%d{MM-dd-yy}-%i.log
appender.F1.layout.type=PatternLayout
appender.F1.layout.pattern=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %5p [T%t] [%x] [%C:%L] %m%n
appender.F1.policies.type=Policies
appender.F1.policies.size.type=SizeBasedTriggeringPolicy
appender.F1.policies.size.size=100MB
appender.F1.strategy.type=DefaultRolloverStrategy
appender.F1.strategy.max=3

#------------------- xREST Core log --------------------------------------
appender.xRestCore.type=RollingFile
appender.xRestCore.name=xRestCore
appender.xRestCore.fileName=C:/temp/documentum/xCPRestCore.log
appender.xRestCore.filePattern=C:/temp/documentum/xCPRestCore-%d{MM-dd-yy}-%i.log
appender.xRestCore.layout.type=PatternLayout
appender.xRestCore.layout.pattern=%p %t %c - %m%n
appender.xRestCore.policies.type=Policies
appender.xRestCore.policies.size.type=SizeBasedTriggeringPolicy
appender.xRestCore.policies.size.size=100MB
appender.xRestCore.strategy.type=DefaultRolloverStrategy
appender.xRestCore.strategy.max=3

#------------------- xREST Security log --------------------------------------
appender.xRestSecurity.type=RollingFile
appender.xRestSecurity.name=xRestSecurity
appender.xRestSecurity.fileName=C:/temp/documentum/xCPRestSecurity.log
appender.xRestSecurity.filePattern=C:/temp/documentum/xCPRestSecurity-%d{MM-dd-yy}-%i.log
appender.xRestSecurity.layout.type=PatternLayout
appender.xRestSecurity.layout.pattern=%p %t %c - %m%n
appender.xRestSecurity.policies.type=Policies
appender.xRestSecurity.policies.size.type=SizeBasedTriggeringPolicy
appender.xRestSecurity.policies.size.size=100MB
appender.xRestSecurity.strategy.type=DefaultRolloverStrategy
appender.xRestSecurity.strategy.max=3

logger.xRestCore.name=com.emc.xcp.rest.core
logger.xRestCore.level=DEBUG
logger.xRestCore.additivity = false
logger.xRestCore.appenderRef.xRestCore.ref=xRestCore

logger.xRestSecurity.name=com.emc.xcp.rest.security
logger.xRestSecurity.level=DEBUG
logger.xRestSecurity.additivity = false
logger.xRestSecurity.appenderRef.xRestSecurity.ref=xRestSecurity

