dfc.session.allow_trusted_login=false
dfc.name=D224_4
dfc.data.dir=C:\\Documentum\\config
dfc.security.keystore.file=C:\\Documentum\\config\\dfc.keystore
dfc.session.secure_connect_default=try_native_first
dfc.tokenstorage.enable=false
dfc.docbroker.host[0]=35.177.194.208
dfc.docbroker.port[0]=1489
dfc.globalregistry.repository=ecmdev_db
dfc.globalregistry.username=dm_bof_registry
dfc.globalregistry.password=AAAAEFLb+74uaxkboV7axWGgbGADi8F+Dz1FhmQ20ei6OswVHFtndbueUCi861341h95uw\=\=
dfc.session.allow_trusted_login=false
dfc.date.format=yyyy-MM-dd HH:mm:ss