dfc.session.allow_trusted_login=false
dfc.name=D224_4
dfc.data.dir=\\Documentum\\config
dfc.security.keystore.file=\\Documentum\\config\\dfc.keystore
dfc.session.secure_connect_default=
dfc.tokenstorage.enable=false
dfc.docbroker.host[0]=
dfc.docbroker.port[0]=
dfc.globalregistry.repository=
dfc.globalregistry.username=
dfc.globalregistry.password=
dfc.session.allow_trusted_login=false
dfc.date.format=yyyy-MM-dd HH:mm:ss